import { ClassA } from "@libs/lib-a";
import { ClassB } from "@libs/lib-b";
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const objectA = new ClassA({ name: "name A", valueA: "value A" });
const objectB = new ClassB({ name: "name B", valueB: "value B" });

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <pre>
          {JSON.stringify({
            name: objectA.name,
            valueA: objectA.valueA,
          }, null, 2)}
        </pre>
        <pre>
          {JSON.stringify({
            name: objectB.name,
            valueB: objectB.valueB,
            didB: objectB.did
          }, null, 2)}
        </pre>
      </main>
    </div>
  )
}
